/*
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RMAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/riskmanagement/parser/antlr/internal/InternalRM.tokens");
	}
}
