/*
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.riskmanagement.parser.antlr.internal.InternalRMParser;
import org.xtext.riskmanagement.services.RMGrammarAccess;

public class RMParser extends AbstractAntlrParser {

	@Inject
	private RMGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRMParser createParser(XtextTokenStream stream) {
		return new InternalRMParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
