/*
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RMGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Model:
		//	{Model}
		//	'Model'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Model} 'Model' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }
		
		//'Model'
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class RiskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Risk");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRisk_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOpportunityParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cUncertaintyParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cThreatParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Risk:
		//	Risk_Impl | Opportunity | Uncertainty | Threat;
		@Override public ParserRule getRule() { return rule; }
		
		//Risk_Impl | Opportunity | Uncertainty | Threat
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Risk_Impl
		public RuleCall getRisk_ImplParserRuleCall_0() { return cRisk_ImplParserRuleCall_0; }
		
		//Opportunity
		public RuleCall getOpportunityParserRuleCall_1() { return cOpportunityParserRuleCall_1; }
		
		//Uncertainty
		public RuleCall getUncertaintyParserRuleCall_2() { return cUncertaintyParserRuleCall_2; }
		
		//Threat
		public RuleCall getThreatParserRuleCall_3() { return cThreatParserRuleCall_3; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class AssetBasedModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.AssetBasedModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssetBasedModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cAssetKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAssetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAssetAssetParserRuleCall_4_0 = (RuleCall)cAssetAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//AssetBasedModel:
		//	'AssetBasedModel'
		//	name=EString
		//	'{'
		//	'asset' asset=Asset
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'AssetBasedModel' name=EString '{' 'asset' asset=Asset '}'
		public Group getGroup() { return cGroup; }
		
		//'AssetBasedModel'
		public Keyword getAssetBasedModelKeyword_0() { return cAssetBasedModelKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'asset'
		public Keyword getAssetKeyword_3() { return cAssetKeyword_3; }
		
		//asset=Asset
		public Assignment getAssetAssignment_4() { return cAssetAssignment_4; }
		
		//Asset
		public RuleCall getAssetAssetParserRuleCall_4_0() { return cAssetAssetParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ScenarioBasedModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.ScenarioBasedModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cScenarioBasedModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cScenarioKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cScenarioAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cScenarioScenarioParserRuleCall_5_0 = (RuleCall)cScenarioAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cScenarioAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cScenarioScenarioParserRuleCall_6_1_0 = (RuleCall)cScenarioAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ScenarioBasedModel:
		//	'ScenarioBasedModel'
		//	name=EString
		//	'{'
		//	'scenario' '{' scenario+=Scenario ("," scenario+=Scenario)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ScenarioBasedModel' name=EString '{' 'scenario' '{' scenario+=Scenario ("," scenario+=Scenario)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'ScenarioBasedModel'
		public Keyword getScenarioBasedModelKeyword_0() { return cScenarioBasedModelKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'scenario'
		public Keyword getScenarioKeyword_3() { return cScenarioKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//scenario+=Scenario
		public Assignment getScenarioAssignment_5() { return cScenarioAssignment_5; }
		
		//Scenario
		public RuleCall getScenarioScenarioParserRuleCall_5_0() { return cScenarioScenarioParserRuleCall_5_0; }
		
		//("," scenario+=Scenario)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//scenario+=Scenario
		public Assignment getScenarioAssignment_6_1() { return cScenarioAssignment_6_1; }
		
		//Scenario
		public RuleCall getScenarioScenarioParserRuleCall_6_1_0() { return cScenarioScenarioParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class AssetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Asset");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHasKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cHasAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cHasVulnerableCrossReference_5_0 = (CrossReference)cHasAssignment_5.eContents().get(0);
		private final RuleCall cHasVulnerableEStringParserRuleCall_5_0_1 = (RuleCall)cHasVulnerableCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cHasAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cHasVulnerableCrossReference_6_1_0 = (CrossReference)cHasAssignment_6_1.eContents().get(0);
		private final RuleCall cHasVulnerableEStringParserRuleCall_6_1_0_1 = (RuleCall)cHasVulnerableCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCausesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cCausesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cCausesRiskParserRuleCall_8_2_0 = (RuleCall)cCausesAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cCausesAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cCausesRiskParserRuleCall_8_3_1_0 = (RuleCall)cCausesAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Asset:
		//	'Asset'
		//	name=EString
		//	'{'
		//	'has' '(' has+=[Vulnerable|EString] ("," has+=[Vulnerable|EString])* ')' ('causes' '{' causes+=Risk (","
		//	causes+=Risk)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Asset' name=EString '{' 'has' '(' has+=[Vulnerable|EString] ("," has+=[Vulnerable|EString])* ')' ('causes' '{'
		//causes+=Risk ("," causes+=Risk)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'Asset'
		public Keyword getAssetKeyword_0() { return cAssetKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'has'
		public Keyword getHasKeyword_3() { return cHasKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//has+=[Vulnerable|EString]
		public Assignment getHasAssignment_5() { return cHasAssignment_5; }
		
		//[Vulnerable|EString]
		public CrossReference getHasVulnerableCrossReference_5_0() { return cHasVulnerableCrossReference_5_0; }
		
		//EString
		public RuleCall getHasVulnerableEStringParserRuleCall_5_0_1() { return cHasVulnerableEStringParserRuleCall_5_0_1; }
		
		//("," has+=[Vulnerable|EString])*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//has+=[Vulnerable|EString]
		public Assignment getHasAssignment_6_1() { return cHasAssignment_6_1; }
		
		//[Vulnerable|EString]
		public CrossReference getHasVulnerableCrossReference_6_1_0() { return cHasVulnerableCrossReference_6_1_0; }
		
		//EString
		public RuleCall getHasVulnerableEStringParserRuleCall_6_1_0_1() { return cHasVulnerableEStringParserRuleCall_6_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//('causes' '{' causes+=Risk ("," causes+=Risk)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'causes'
		public Keyword getCausesKeyword_8_0() { return cCausesKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//causes+=Risk
		public Assignment getCausesAssignment_8_2() { return cCausesAssignment_8_2; }
		
		//Risk
		public RuleCall getCausesRiskParserRuleCall_8_2_0() { return cCausesRiskParserRuleCall_8_2_0; }
		
		//("," causes+=Risk)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//causes+=Risk
		public Assignment getCausesAssignment_8_3_1() { return cCausesAssignment_8_3_1; }
		
		//Risk
		public RuleCall getCausesRiskParserRuleCall_8_3_1_0() { return cCausesRiskParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class VulnerableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Vulnerable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVulnerableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIndicatesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cIndicatesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cIndicatesConsequenceCrossReference_5_0 = (CrossReference)cIndicatesAssignment_5.eContents().get(0);
		private final RuleCall cIndicatesConsequenceEStringParserRuleCall_5_0_1 = (RuleCall)cIndicatesConsequenceCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cIndicatesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cIndicatesConsequenceCrossReference_6_1_0 = (CrossReference)cIndicatesAssignment_6_1.eContents().get(0);
		private final RuleCall cIndicatesConsequenceEStringParserRuleCall_6_1_0_1 = (RuleCall)cIndicatesConsequenceCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Vulnerable:
		//	'Vulnerable'
		//	name=EString
		//	'{'
		//	'indicates' '(' indicates+=[Consequence|EString] ("," indicates+=[Consequence|EString])* ')'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Vulnerable' name=EString '{' 'indicates' '(' indicates+=[Consequence|EString] ("," indicates+=[Consequence|EString])*
		//')' '}'
		public Group getGroup() { return cGroup; }
		
		//'Vulnerable'
		public Keyword getVulnerableKeyword_0() { return cVulnerableKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'indicates'
		public Keyword getIndicatesKeyword_3() { return cIndicatesKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//indicates+=[Consequence|EString]
		public Assignment getIndicatesAssignment_5() { return cIndicatesAssignment_5; }
		
		//[Consequence|EString]
		public CrossReference getIndicatesConsequenceCrossReference_5_0() { return cIndicatesConsequenceCrossReference_5_0; }
		
		//EString
		public RuleCall getIndicatesConsequenceEStringParserRuleCall_5_0_1() { return cIndicatesConsequenceEStringParserRuleCall_5_0_1; }
		
		//("," indicates+=[Consequence|EString])*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//indicates+=[Consequence|EString]
		public Assignment getIndicatesAssignment_6_1() { return cIndicatesAssignment_6_1; }
		
		//[Consequence|EString]
		public CrossReference getIndicatesConsequenceCrossReference_6_1_0() { return cIndicatesConsequenceCrossReference_6_1_0; }
		
		//EString
		public RuleCall getIndicatesConsequenceEStringParserRuleCall_6_1_0_1() { return cIndicatesConsequenceEStringParserRuleCall_6_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class Risk_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Risk_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRiskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cViewKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cViewAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cViewViewEnumRuleCall_4_0 = (RuleCall)cViewAssignment_4.eContents().get(0);
		private final Keyword cOccurrenceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOccurrenceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOccurrenceEIntParserRuleCall_6_0 = (RuleCall)cOccurrenceAssignment_6.eContents().get(0);
		private final Keyword cImpactKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cImpactAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cImpactEIntParserRuleCall_8_0 = (RuleCall)cImpactAssignment_8.eContents().get(0);
		private final Keyword cProducesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cProducesAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cProducesConsequenceParserRuleCall_11_0 = (RuleCall)cProducesAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cProducesAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cProducesConsequenceParserRuleCall_12_1_0 = (RuleCall)cProducesAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Risk_Impl Risk:
		//	'Risk'
		//	name=EString
		//	'{'
		//	'view' view=View
		//	'occurrence' occurrence=EInt
		//	'impact' impact=EInt
		//	'produces' '{' produces+=Consequence ("," produces+=Consequence)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Risk' name=EString '{' 'view' view=View 'occurrence' occurrence=EInt 'impact' impact=EInt 'produces' '{'
		//produces+=Consequence ("," produces+=Consequence)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Risk'
		public Keyword getRiskKeyword_0() { return cRiskKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'view'
		public Keyword getViewKeyword_3() { return cViewKeyword_3; }
		
		//view=View
		public Assignment getViewAssignment_4() { return cViewAssignment_4; }
		
		//View
		public RuleCall getViewViewEnumRuleCall_4_0() { return cViewViewEnumRuleCall_4_0; }
		
		//'occurrence'
		public Keyword getOccurrenceKeyword_5() { return cOccurrenceKeyword_5; }
		
		//occurrence=EInt
		public Assignment getOccurrenceAssignment_6() { return cOccurrenceAssignment_6; }
		
		//EInt
		public RuleCall getOccurrenceEIntParserRuleCall_6_0() { return cOccurrenceEIntParserRuleCall_6_0; }
		
		//'impact'
		public Keyword getImpactKeyword_7() { return cImpactKeyword_7; }
		
		//impact=EInt
		public Assignment getImpactAssignment_8() { return cImpactAssignment_8; }
		
		//EInt
		public RuleCall getImpactEIntParserRuleCall_8_0() { return cImpactEIntParserRuleCall_8_0; }
		
		//'produces'
		public Keyword getProducesKeyword_9() { return cProducesKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//produces+=Consequence
		public Assignment getProducesAssignment_11() { return cProducesAssignment_11; }
		
		//Consequence
		public RuleCall getProducesConsequenceParserRuleCall_11_0() { return cProducesConsequenceParserRuleCall_11_0; }
		
		//("," produces+=Consequence)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//produces+=Consequence
		public Assignment getProducesAssignment_12_1() { return cProducesAssignment_12_1; }
		
		//Consequence
		public RuleCall getProducesConsequenceParserRuleCall_12_1_0() { return cProducesConsequenceParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class ConsequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Consequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConsequenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cConsequenceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Consequence:
		//	{Consequence}
		//	'Consequence'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Consequence} 'Consequence' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Consequence}
		public Action getConsequenceAction_0() { return cConsequenceAction_0; }
		
		//'Consequence'
		public Keyword getConsequenceKeyword_1() { return cConsequenceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class OpportunityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Opportunity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpportunityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cViewKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cViewAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cViewViewEnumRuleCall_4_0 = (RuleCall)cViewAssignment_4.eContents().get(0);
		private final Keyword cOccurrenceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOccurrenceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOccurrenceEIntParserRuleCall_6_0 = (RuleCall)cOccurrenceAssignment_6.eContents().get(0);
		private final Keyword cImpactKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cImpactAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cImpactEIntParserRuleCall_8_0 = (RuleCall)cImpactAssignment_8.eContents().get(0);
		private final Keyword cProducesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cProducesAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cProducesConsequenceParserRuleCall_11_0 = (RuleCall)cProducesAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cProducesAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cProducesConsequenceParserRuleCall_12_1_0 = (RuleCall)cProducesAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Opportunity:
		//	'Opportunity'
		//	name=EString
		//	'{'
		//	'view' view=View
		//	'occurrence' occurrence=EInt
		//	'impact' impact=EInt
		//	'produces' '{' produces+=Consequence ("," produces+=Consequence)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Opportunity' name=EString '{' 'view' view=View 'occurrence' occurrence=EInt 'impact' impact=EInt 'produces' '{'
		//produces+=Consequence ("," produces+=Consequence)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Opportunity'
		public Keyword getOpportunityKeyword_0() { return cOpportunityKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'view'
		public Keyword getViewKeyword_3() { return cViewKeyword_3; }
		
		//view=View
		public Assignment getViewAssignment_4() { return cViewAssignment_4; }
		
		//View
		public RuleCall getViewViewEnumRuleCall_4_0() { return cViewViewEnumRuleCall_4_0; }
		
		//'occurrence'
		public Keyword getOccurrenceKeyword_5() { return cOccurrenceKeyword_5; }
		
		//occurrence=EInt
		public Assignment getOccurrenceAssignment_6() { return cOccurrenceAssignment_6; }
		
		//EInt
		public RuleCall getOccurrenceEIntParserRuleCall_6_0() { return cOccurrenceEIntParserRuleCall_6_0; }
		
		//'impact'
		public Keyword getImpactKeyword_7() { return cImpactKeyword_7; }
		
		//impact=EInt
		public Assignment getImpactAssignment_8() { return cImpactAssignment_8; }
		
		//EInt
		public RuleCall getImpactEIntParserRuleCall_8_0() { return cImpactEIntParserRuleCall_8_0; }
		
		//'produces'
		public Keyword getProducesKeyword_9() { return cProducesKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//produces+=Consequence
		public Assignment getProducesAssignment_11() { return cProducesAssignment_11; }
		
		//Consequence
		public RuleCall getProducesConsequenceParserRuleCall_11_0() { return cProducesConsequenceParserRuleCall_11_0; }
		
		//("," produces+=Consequence)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//produces+=Consequence
		public Assignment getProducesAssignment_12_1() { return cProducesAssignment_12_1; }
		
		//Consequence
		public RuleCall getProducesConsequenceParserRuleCall_12_1_0() { return cProducesConsequenceParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class UncertaintyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Uncertainty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUncertaintyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cViewKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cViewAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cViewViewEnumRuleCall_4_0 = (RuleCall)cViewAssignment_4.eContents().get(0);
		private final Keyword cOccurrenceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOccurrenceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOccurrenceEIntParserRuleCall_6_0 = (RuleCall)cOccurrenceAssignment_6.eContents().get(0);
		private final Keyword cImpactKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cImpactAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cImpactEIntParserRuleCall_8_0 = (RuleCall)cImpactAssignment_8.eContents().get(0);
		private final Keyword cProducesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cProducesAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cProducesConsequenceParserRuleCall_11_0 = (RuleCall)cProducesAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cProducesAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cProducesConsequenceParserRuleCall_12_1_0 = (RuleCall)cProducesAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Uncertainty:
		//	'Uncertainty'
		//	name=EString
		//	'{'
		//	'view' view=View
		//	'occurrence' occurrence=EInt
		//	'impact' impact=EInt
		//	'produces' '{' produces+=Consequence ("," produces+=Consequence)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Uncertainty' name=EString '{' 'view' view=View 'occurrence' occurrence=EInt 'impact' impact=EInt 'produces' '{'
		//produces+=Consequence ("," produces+=Consequence)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Uncertainty'
		public Keyword getUncertaintyKeyword_0() { return cUncertaintyKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'view'
		public Keyword getViewKeyword_3() { return cViewKeyword_3; }
		
		//view=View
		public Assignment getViewAssignment_4() { return cViewAssignment_4; }
		
		//View
		public RuleCall getViewViewEnumRuleCall_4_0() { return cViewViewEnumRuleCall_4_0; }
		
		//'occurrence'
		public Keyword getOccurrenceKeyword_5() { return cOccurrenceKeyword_5; }
		
		//occurrence=EInt
		public Assignment getOccurrenceAssignment_6() { return cOccurrenceAssignment_6; }
		
		//EInt
		public RuleCall getOccurrenceEIntParserRuleCall_6_0() { return cOccurrenceEIntParserRuleCall_6_0; }
		
		//'impact'
		public Keyword getImpactKeyword_7() { return cImpactKeyword_7; }
		
		//impact=EInt
		public Assignment getImpactAssignment_8() { return cImpactAssignment_8; }
		
		//EInt
		public RuleCall getImpactEIntParserRuleCall_8_0() { return cImpactEIntParserRuleCall_8_0; }
		
		//'produces'
		public Keyword getProducesKeyword_9() { return cProducesKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//produces+=Consequence
		public Assignment getProducesAssignment_11() { return cProducesAssignment_11; }
		
		//Consequence
		public RuleCall getProducesConsequenceParserRuleCall_11_0() { return cProducesConsequenceParserRuleCall_11_0; }
		
		//("," produces+=Consequence)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//produces+=Consequence
		public Assignment getProducesAssignment_12_1() { return cProducesAssignment_12_1; }
		
		//Consequence
		public RuleCall getProducesConsequenceParserRuleCall_12_1_0() { return cProducesConsequenceParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class ThreatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Threat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cThreatKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cViewKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cViewAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cViewViewEnumRuleCall_4_0 = (RuleCall)cViewAssignment_4.eContents().get(0);
		private final Keyword cOccurrenceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOccurrenceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOccurrenceEIntParserRuleCall_6_0 = (RuleCall)cOccurrenceAssignment_6.eContents().get(0);
		private final Keyword cImpactKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cImpactAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cImpactEIntParserRuleCall_8_0 = (RuleCall)cImpactAssignment_8.eContents().get(0);
		private final Keyword cProducesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cProducesAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cProducesConsequenceParserRuleCall_11_0 = (RuleCall)cProducesAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cProducesAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cProducesConsequenceParserRuleCall_12_1_0 = (RuleCall)cProducesAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Threat:
		//	'Threat'
		//	name=EString
		//	'{'
		//	'view' view=View
		//	'occurrence' occurrence=EInt
		//	'impact' impact=EInt
		//	'produces' '{' produces+=Consequence ("," produces+=Consequence)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Threat' name=EString '{' 'view' view=View 'occurrence' occurrence=EInt 'impact' impact=EInt 'produces' '{'
		//produces+=Consequence ("," produces+=Consequence)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Threat'
		public Keyword getThreatKeyword_0() { return cThreatKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'view'
		public Keyword getViewKeyword_3() { return cViewKeyword_3; }
		
		//view=View
		public Assignment getViewAssignment_4() { return cViewAssignment_4; }
		
		//View
		public RuleCall getViewViewEnumRuleCall_4_0() { return cViewViewEnumRuleCall_4_0; }
		
		//'occurrence'
		public Keyword getOccurrenceKeyword_5() { return cOccurrenceKeyword_5; }
		
		//occurrence=EInt
		public Assignment getOccurrenceAssignment_6() { return cOccurrenceAssignment_6; }
		
		//EInt
		public RuleCall getOccurrenceEIntParserRuleCall_6_0() { return cOccurrenceEIntParserRuleCall_6_0; }
		
		//'impact'
		public Keyword getImpactKeyword_7() { return cImpactKeyword_7; }
		
		//impact=EInt
		public Assignment getImpactAssignment_8() { return cImpactAssignment_8; }
		
		//EInt
		public RuleCall getImpactEIntParserRuleCall_8_0() { return cImpactEIntParserRuleCall_8_0; }
		
		//'produces'
		public Keyword getProducesKeyword_9() { return cProducesKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//produces+=Consequence
		public Assignment getProducesAssignment_11() { return cProducesAssignment_11; }
		
		//Consequence
		public RuleCall getProducesConsequenceParserRuleCall_11_0() { return cProducesConsequenceParserRuleCall_11_0; }
		
		//("," produces+=Consequence)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//produces+=Consequence
		public Assignment getProducesAssignment_12_1() { return cProducesAssignment_12_1; }
		
		//Consequence
		public RuleCall getProducesConsequenceParserRuleCall_12_1_0() { return cProducesConsequenceParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class ScenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Scenario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cScenarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSubscenarioKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cSubscenarioAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cSubscenarioScenarioParserRuleCall_3_2_0 = (RuleCall)cSubscenarioAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cSubscenarioAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cSubscenarioScenarioParserRuleCall_3_3_1_0 = (RuleCall)cSubscenarioAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cActionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cActionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cActionActionParserRuleCall_6_0 = (RuleCall)cActionAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cActionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cActionActionParserRuleCall_7_1_0 = (RuleCall)cActionAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Scenario:
		//	'Scenario'
		//	name=EString
		//	'{' ('subscenario' '{' subscenario+=Scenario ("," subscenario+=Scenario)* '}')?
		//	'action' '{' action+=Action ("," action+=Action)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Scenario' name=EString '{' ('subscenario' '{' subscenario+=Scenario ("," subscenario+=Scenario)* '}')? 'action' '{'
		//action+=Action ("," action+=Action)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Scenario'
		public Keyword getScenarioKeyword_0() { return cScenarioKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('subscenario' '{' subscenario+=Scenario ("," subscenario+=Scenario)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'subscenario'
		public Keyword getSubscenarioKeyword_3_0() { return cSubscenarioKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//subscenario+=Scenario
		public Assignment getSubscenarioAssignment_3_2() { return cSubscenarioAssignment_3_2; }
		
		//Scenario
		public RuleCall getSubscenarioScenarioParserRuleCall_3_2_0() { return cSubscenarioScenarioParserRuleCall_3_2_0; }
		
		//("," subscenario+=Scenario)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//subscenario+=Scenario
		public Assignment getSubscenarioAssignment_3_3_1() { return cSubscenarioAssignment_3_3_1; }
		
		//Scenario
		public RuleCall getSubscenarioScenarioParserRuleCall_3_3_1_0() { return cSubscenarioScenarioParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'action'
		public Keyword getActionKeyword_4() { return cActionKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//action+=Action
		public Assignment getActionAssignment_6() { return cActionAssignment_6; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_6_0() { return cActionActionParserRuleCall_6_0; }
		
		//("," action+=Action)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//action+=Action
		public Assignment getActionAssignment_7_1() { return cActionAssignment_7_1; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_7_1_0() { return cActionActionParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAssetKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAssetAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAssetAssetParserRuleCall_4_2_0 = (RuleCall)cAssetAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAssetAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cAssetAssetParserRuleCall_4_3_1_0 = (RuleCall)cAssetAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Action:
		//	{Action}
		//	'Action'
		//	name=EString
		//	'{' ('asset' '{' asset+=Asset ("," asset+=Asset)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Action} 'Action' name=EString '{' ('asset' '{' asset+=Asset ("," asset+=Asset)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Action}
		public Action getActionAction_0() { return cActionAction_0; }
		
		//'Action'
		public Keyword getActionKeyword_1() { return cActionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('asset' '{' asset+=Asset ("," asset+=Asset)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'asset'
		public Keyword getAssetKeyword_4_0() { return cAssetKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//asset+=Asset
		public Assignment getAssetAssignment_4_2() { return cAssetAssignment_4_2; }
		
		//Asset
		public RuleCall getAssetAssetParserRuleCall_4_2_0() { return cAssetAssetParserRuleCall_4_2_0; }
		
		//("," asset+=Asset)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//asset+=Asset
		public Assignment getAssetAssignment_4_3_1() { return cAssetAssignment_4_3_1; }
		
		//Asset
		public RuleCall getAssetAssetParserRuleCall_4_3_1_0() { return cAssetAssetParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	public class ViewElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.riskmanagement.RM.View");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPositiveEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPositivePositiveKeyword_0_0 = (Keyword)cPositiveEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNeutralEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNeutralNeutralKeyword_1_0 = (Keyword)cNeutralEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNegativeEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNegativeNegativeKeyword_2_0 = (Keyword)cNegativeEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum View:
		//	Positive | Neutral | Negative;
		public EnumRule getRule() { return rule; }
		
		//Positive | Neutral | Negative
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Positive
		public EnumLiteralDeclaration getPositiveEnumLiteralDeclaration_0() { return cPositiveEnumLiteralDeclaration_0; }
		
		//'Positive'
		public Keyword getPositivePositiveKeyword_0_0() { return cPositivePositiveKeyword_0_0; }
		
		//Neutral
		public EnumLiteralDeclaration getNeutralEnumLiteralDeclaration_1() { return cNeutralEnumLiteralDeclaration_1; }
		
		//'Neutral'
		public Keyword getNeutralNeutralKeyword_1_0() { return cNeutralNeutralKeyword_1_0; }
		
		//Negative
		public EnumLiteralDeclaration getNegativeEnumLiteralDeclaration_2() { return cNegativeEnumLiteralDeclaration_2; }
		
		//'Negative'
		public Keyword getNegativeNegativeKeyword_2_0() { return cNegativeNegativeKeyword_2_0; }
	}
	
	private final ModelElements pModel;
	private final RiskElements pRisk;
	private final EStringElements pEString;
	private final AssetBasedModelElements pAssetBasedModel;
	private final ScenarioBasedModelElements pScenarioBasedModel;
	private final AssetElements pAsset;
	private final VulnerableElements pVulnerable;
	private final Risk_ImplElements pRisk_Impl;
	private final ConsequenceElements pConsequence;
	private final ViewElements eView;
	private final EIntElements pEInt;
	private final OpportunityElements pOpportunity;
	private final UncertaintyElements pUncertainty;
	private final ThreatElements pThreat;
	private final ScenarioElements pScenario;
	private final ActionElements pAction;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RMGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pRisk = new RiskElements();
		this.pEString = new EStringElements();
		this.pAssetBasedModel = new AssetBasedModelElements();
		this.pScenarioBasedModel = new ScenarioBasedModelElements();
		this.pAsset = new AssetElements();
		this.pVulnerable = new VulnerableElements();
		this.pRisk_Impl = new Risk_ImplElements();
		this.pConsequence = new ConsequenceElements();
		this.eView = new ViewElements();
		this.pEInt = new EIntElements();
		this.pOpportunity = new OpportunityElements();
		this.pUncertainty = new UncertaintyElements();
		this.pThreat = new ThreatElements();
		this.pScenario = new ScenarioElements();
		this.pAction = new ActionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.riskmanagement.RM".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	{Model}
	//	'Model'
	//	name=EString;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Risk:
	//	Risk_Impl | Opportunity | Uncertainty | Threat;
	public RiskElements getRiskAccess() {
		return pRisk;
	}
	
	public ParserRule getRiskRule() {
		return getRiskAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//AssetBasedModel:
	//	'AssetBasedModel'
	//	name=EString
	//	'{'
	//	'asset' asset=Asset
	//	'}';
	public AssetBasedModelElements getAssetBasedModelAccess() {
		return pAssetBasedModel;
	}
	
	public ParserRule getAssetBasedModelRule() {
		return getAssetBasedModelAccess().getRule();
	}
	
	//ScenarioBasedModel:
	//	'ScenarioBasedModel'
	//	name=EString
	//	'{'
	//	'scenario' '{' scenario+=Scenario ("," scenario+=Scenario)* '}'
	//	'}';
	public ScenarioBasedModelElements getScenarioBasedModelAccess() {
		return pScenarioBasedModel;
	}
	
	public ParserRule getScenarioBasedModelRule() {
		return getScenarioBasedModelAccess().getRule();
	}
	
	//Asset:
	//	'Asset'
	//	name=EString
	//	'{'
	//	'has' '(' has+=[Vulnerable|EString] ("," has+=[Vulnerable|EString])* ')' ('causes' '{' causes+=Risk (","
	//	causes+=Risk)* '}')?
	//	'}';
	public AssetElements getAssetAccess() {
		return pAsset;
	}
	
	public ParserRule getAssetRule() {
		return getAssetAccess().getRule();
	}
	
	//Vulnerable:
	//	'Vulnerable'
	//	name=EString
	//	'{'
	//	'indicates' '(' indicates+=[Consequence|EString] ("," indicates+=[Consequence|EString])* ')'
	//	'}';
	public VulnerableElements getVulnerableAccess() {
		return pVulnerable;
	}
	
	public ParserRule getVulnerableRule() {
		return getVulnerableAccess().getRule();
	}
	
	//Risk_Impl Risk:
	//	'Risk'
	//	name=EString
	//	'{'
	//	'view' view=View
	//	'occurrence' occurrence=EInt
	//	'impact' impact=EInt
	//	'produces' '{' produces+=Consequence ("," produces+=Consequence)* '}'
	//	'}';
	public Risk_ImplElements getRisk_ImplAccess() {
		return pRisk_Impl;
	}
	
	public ParserRule getRisk_ImplRule() {
		return getRisk_ImplAccess().getRule();
	}
	
	//Consequence:
	//	{Consequence}
	//	'Consequence'
	//	name=EString;
	public ConsequenceElements getConsequenceAccess() {
		return pConsequence;
	}
	
	public ParserRule getConsequenceRule() {
		return getConsequenceAccess().getRule();
	}
	
	//enum View:
	//	Positive | Neutral | Negative;
	public ViewElements getViewAccess() {
		return eView;
	}
	
	public EnumRule getViewRule() {
		return getViewAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Opportunity:
	//	'Opportunity'
	//	name=EString
	//	'{'
	//	'view' view=View
	//	'occurrence' occurrence=EInt
	//	'impact' impact=EInt
	//	'produces' '{' produces+=Consequence ("," produces+=Consequence)* '}'
	//	'}';
	public OpportunityElements getOpportunityAccess() {
		return pOpportunity;
	}
	
	public ParserRule getOpportunityRule() {
		return getOpportunityAccess().getRule();
	}
	
	//Uncertainty:
	//	'Uncertainty'
	//	name=EString
	//	'{'
	//	'view' view=View
	//	'occurrence' occurrence=EInt
	//	'impact' impact=EInt
	//	'produces' '{' produces+=Consequence ("," produces+=Consequence)* '}'
	//	'}';
	public UncertaintyElements getUncertaintyAccess() {
		return pUncertainty;
	}
	
	public ParserRule getUncertaintyRule() {
		return getUncertaintyAccess().getRule();
	}
	
	//Threat:
	//	'Threat'
	//	name=EString
	//	'{'
	//	'view' view=View
	//	'occurrence' occurrence=EInt
	//	'impact' impact=EInt
	//	'produces' '{' produces+=Consequence ("," produces+=Consequence)* '}'
	//	'}';
	public ThreatElements getThreatAccess() {
		return pThreat;
	}
	
	public ParserRule getThreatRule() {
		return getThreatAccess().getRule();
	}
	
	//Scenario:
	//	'Scenario'
	//	name=EString
	//	'{' ('subscenario' '{' subscenario+=Scenario ("," subscenario+=Scenario)* '}')?
	//	'action' '{' action+=Action ("," action+=Action)* '}'
	//	'}';
	public ScenarioElements getScenarioAccess() {
		return pScenario;
	}
	
	public ParserRule getScenarioRule() {
		return getScenarioAccess().getRule();
	}
	
	//Action:
	//	{Action}
	//	'Action'
	//	name=EString
	//	'{' ('asset' '{' asset+=Asset ("," asset+=Asset)* '}')?
	//	'}';
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
