/**
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.ui.contentassist;

import org.xtext.riskmanagement.ui.contentassist.AbstractRMProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RMProposalProvider extends AbstractRMProposalProvider {
}
