/*
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RMStandaloneSetup extends RMStandaloneSetupGenerated {

	def static void doSetup() {
		new RMStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
