/*
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRMScopeProvider extends DelegatingScopeProvider {
}
