/**
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.validation;

import org.xtext.riskmanagement.validation.AbstractRMValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RMValidator extends AbstractRMValidator {
}
