/**
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.scoping;

import org.xtext.riskmanagement.scoping.AbstractRMScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RMScopeProvider extends AbstractRMScopeProvider {
}
