/**
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.riskmanagement.RMRuntimeModule;
import org.xtext.riskmanagement.RMStandaloneSetup;
import org.xtext.riskmanagement.ide.RMIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RMIdeSetup extends RMStandaloneSetup {
  @Override
  public Injector createInjector() {
    RMRuntimeModule _rMRuntimeModule = new RMRuntimeModule();
    RMIdeModule _rMIdeModule = new RMIdeModule();
    return Guice.createInjector(Modules2.mixin(_rMRuntimeModule, _rMIdeModule));
  }
}
