/**
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement.ide;

import org.xtext.riskmanagement.ide.AbstractRMIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RMIdeModule extends AbstractRMIdeModule {
}
