/**
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement;

import org.xtext.riskmanagement.AbstractRMRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RMRuntimeModule extends AbstractRMRuntimeModule {
}
