/**
 * generated by Xtext 2.16.0
 */
package org.xtext.riskmanagement;

import org.xtext.riskmanagement.RMStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RMStandaloneSetup extends RMStandaloneSetupGenerated {
  public static void doSetup() {
    new RMStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
